"""
Report Generation & Email Service
- Generates a text-based study report for a child
- Downloads as .txt file
- Emails the same report to the parent
"""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session
from datetime import datetime, timedelta
import smtplib
from email.message import EmailMessage
import math

from app.database.db import get_db
from app.database.models import StudySession, Child, Parent, Task, AIPrompt
from app.core.auth import get_current_parent

router = APIRouter(prefix="/report", tags=["Report"])

EMAIL_USER = "berimadhav911@gmail.com"
EMAIL_PASS = "sgpp yzgy vcyo pjwk"


def generate_report_text(child, sessions, completed_tasks_count, ai_prompts, weekly_data):
    """Generate a clean text report for the child's study analytics."""

    now_ist = (datetime.utcnow() + timedelta(hours=5, minutes=30)).strftime(
        "%I:%M %p IST on %d %b %Y"
    )

    total_study_minutes = 0
    total_alerts = 0
    completed_sessions = 0
    terminated_sessions = 0

    for s in sessions:
        total_alerts += s.alert_count
        if s.status == "completed":
            completed_sessions += 1
            if s.task:
                total_study_minutes += s.task.duration_minutes
        elif s.status == "terminated":
            terminated_sessions += 1
            if s.start_time and s.end_time:
                diff = s.end_time - s.start_time
                total_study_minutes += max(1, math.ceil(diff.total_seconds() / 60.0))

    hours = total_study_minutes // 60
    mins = total_study_minutes % 60

    # Session history (last 10)
    session_lines = ""
    recent = sorted(sessions, key=lambda x: x.start_time or datetime.min, reverse=True)[:10]
    for i, s in enumerate(recent, 1):
        start = s.start_time.strftime("%d %b %Y, %I:%M %p") if s.start_time else "N/A"
        status_emoji = "✅" if s.status == "completed" else "❌"
        task_title = s.task.title if s.task else "Unknown"
        session_lines += f"   {i}. {status_emoji} {task_title} — {start} (Alerts: {s.alert_count})\n"

    if not session_lines:
        session_lines = "   No sessions recorded yet.\n"

    # AI topics
    topic_lines = ""
    for i, p in enumerate(ai_prompts[:8], 1):
        topic_lines += f"   {i}. \"{p.prompt}\"\n"
    if not topic_lines:
        topic_lines = "   No AI queries made yet.\n"

    # Weekly breakdown
    weekly_lines = ""
    for d in weekly_data:
        bar = "█" * min(d["studyMinutes"], 30) if d["studyMinutes"] > 0 else "—"
        weekly_lines += f"   {d['day']:>3}: {bar} {d['studyMinutes']} min  |  ⚠ {d['alerts']} alerts  |  🤖 {d['queries']} queries\n"

    report = f"""
╔══════════════════════════════════════════════════════════════╗
║              PADHLE BHAI 🫵 — STUDY REPORT                  ║
╚══════════════════════════════════════════════════════════════╝

  Student Name    : {child.name}
  Report Generated: {now_ist}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 PERFORMANCE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   📕 Total Study Time     : {hours}h {mins}m
   ⚠️  Total Focus Alerts   : {total_alerts}
   ✅ Completed Tasks      : {completed_tasks_count}
   ❌ Terminated Sessions  : {terminated_sessions}
   🤖 AI Buddy Queries     : {len(ai_prompts)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📅 THIS WEEK'S DAILY BREAKDOWN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{weekly_lines}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 RECENT SESSION HISTORY (Last 10)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{session_lines}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚡ TOPICS THAT NEED REVISION (AI Buddy Queries)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{topic_lines}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  💡 Tip: If focus alerts are high, consider shorter study
     sessions with breaks in between.

  Generated by Padhle Bhai 🫵 — Intelligent Study System
  
"""
    return report


def email_report(parent_email: str, child_name: str, report_text: str):
    """Send the generated report to the parent's email."""
    try:
        msg = EmailMessage()
        msg["Subject"] = f"📊 Weekly Study Report for {child_name} — Padhle Bhai"
        msg["From"] = f"Padhle Bhai!! <{EMAIL_USER}>"
        msg["To"] = parent_email
        msg.set_content(report_text)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_USER, EMAIL_PASS)
            server.send_message(msg)
        print(f"✅ [report] Study report emailed to {parent_email}")
    except Exception as e:
        print(f"❌ [report] Email failed: {str(e)}")


def get_weekly_data(sessions, ai_prompts):
    """Calculate daily breakdown for the current week."""
    now = datetime.utcnow()
    monday_start = (now - timedelta(days=now.weekday())).replace(
        hour=0, minute=0, second=0, microsecond=0
    )

    daily_data = {
        i: {"day": d, "studyMinutes": 0, "alerts": 0, "queries": 0}
        for i, d in enumerate(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
    }

    for session in sessions:
        if session.start_time and session.start_time >= monday_start:
            day_idx = session.start_time.weekday()
            daily_data[day_idx]["alerts"] += session.alert_count
            if session.status == "completed" and session.task:
                daily_data[day_idx]["studyMinutes"] += session.task.duration_minutes
            elif session.status == "terminated" and session.end_time:
                diff = session.end_time - session.start_time
                daily_data[day_idx]["studyMinutes"] += max(
                    1, math.ceil(diff.total_seconds() / 60.0)
                )

    for prompt in ai_prompts:
        if prompt.created_at and prompt.created_at >= monday_start:
            day_idx = prompt.created_at.weekday()
            daily_data[day_idx]["queries"] += 1

    return [daily_data[i] for i in range(7)]


@router.get("/download/{child_id}")
def download_report(
    child_id: int,
    db: Session = Depends(get_db),
    current_parent: Parent = Depends(get_current_parent),
):
    child = (
        db.query(Child)
        .filter(Child.id == child_id, Child.parent_id == current_parent.id)
        .first()
    )
    if not child:
        raise HTTPException(status_code=404, detail="Child not found")

    sessions = db.query(StudySession).filter(StudySession.child_id == child_id).all()
    completed_tasks = (
        db.query(Task).filter(Task.child_id == child_id, Task.is_completed == 1).count()
    )
    ai_prompts = (
        db.query(AIPrompt)
        .filter(AIPrompt.child_id == child_id)
        .order_by(AIPrompt.created_at.desc())
        .all()
    )

    weekly_data = get_weekly_data(sessions, ai_prompts)
    report_text = generate_report_text(child, sessions, completed_tasks, ai_prompts, weekly_data)

    # Also email the report to the parent
    parent = db.query(Parent).filter(Parent.id == current_parent.id).first()
    if parent and parent.email:
        email_report(parent.email, child.name, report_text)

    return PlainTextResponse(
        content=report_text,
        media_type="text/plain",
        headers={
            "Content-Disposition": f'attachment; filename="PadhleBhai_Report_{child.name}_{datetime.utcnow().strftime("%Y%m%d")}.txt"'
        },
    )
